### ISSUE TITLE
nginx static page is not working

### ISSUE THREAD

**Issue by bparanj** [crslade/todo-sunzi-deploy#3]
I am getting this error:

0:08:02 [alert] 10070#0: unlink() "/run/nginx.pid" failed (2: No such file or directory)
2015/06/23 00:08:02 [alert] 10193#0: unlink() "/run/nginx.pid" failed (2: No such file or directory)
2015/06/23 00:08:02 [alert] 10184#0: unlink() "/run/nginx.pid" failed (2: No such file or directory)
2015/06/23 00:08:02 [alert] 10200#0: unlink() "/run/nginx.pid" failed (2: No such file or directory)
2015/06/23 00:43:49 [crit] 4842#0: pread() "/etc/nginx/sites-enabled/carmel" failed (21: Is a directory)
2015/06/23 00:48:10 [crit] 5108#0: pread() "/etc/nginx/sites-enabled/carmel" failed (21: Is a directory)
2015/06/23 00:54:09 [crit] 5444#0: pread() "/etc/nginx/sites-enabled/carmel" failed (21: Is a directory)

When I access my site. Your sample app does not have nginx configuration file. Could you please how to use a simple static config file and modify the recipe to get it working?

**Comment by crslade** [comment]
I cannot reproduce this error. Any more details?
